on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
    paths: ["src/stories/**"]
name: Publish stories if changed

jobs:
  checkout-install-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install Node Modules
        run: npm i
      - name: Instal Playwright
        run: npx playwright install --with-deps
      - name: Test Storybook
        run: npm run storybook && npm run test-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_TOKEN}}
