on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
    paths: ["src/stories/**"]
name: Publish stories if changed

jobs:
  checkout-install-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node Modules
        run: npm i
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_TOKEN}}
