on:
  pull_request:
    types:
      - opened
    branches:
      - master
    paths: ["src/stories/**"]
name: Publish stories if changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Instal Playwright
        run: npx playwright install --with-deps
      - name: Install Node Modules
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'
      
      - name: Test Storybook
        run: npm run storybook && npm run test-storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{secrets.CHROMATIC_TOKEN}}
