on:
  push:
    branches:
      - master
    paths: ['src/stories/**']
name: Publish stories if changed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Node Modules
      run: npm install
    - name: Test Storybook
      run: npm run storybook && npm run test-storybook
    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        projectToken:$((secrets.CHROMATIC_TOKEN}}
            
